### ISSUE TITLE
Stylize code snippets

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#1]
Inline code snippets are getting lost amongst the text. We may want to stylize these a bit to improve readability:

Currently:

![image](https://cloud.githubusercontent.com/assets/371943/12175677/93797bd6-b531-11e5-92d7-4f1fc7849337.png)

Quick idea:

![image](https://cloud.githubusercontent.com/assets/371943/12175700/adde5d84-b531-11e5-85df-615488a94489.png)

**Comment by eturk** [comment]
Some syntax highlighting/styling was added with 1a39433a217efd24f81cdfc9c288823369c69178.
