### ISSUE TITLE
Migration docs from v1

### ISSUE THREAD

**Issue by sskylar** [siteleaf/learn.siteleaf.com#13]
We should include docs for people coming from v1

- http://www.siteleaf.com/help/v2/
- http://www.siteleaf.com/help/v2/improved-metadata-in-v2/
- http://www.siteleaf.com/help/v2/export-v1
- http://www.siteleaf.com/help/v2/gem

**Comment by eturk** [comment]
Added in 883b29d144a299836930a2443fd85c634a4f4c3f.
