### ISSUE TITLE
Jekyll compatibility callouts

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#20]
I dig this idea: https://oak.slack.com/archives/siteleaf/p1453221551000142

**Comment by larryfox** [comment]
That versions live, I'm kind of using it as a generic callout. http://learn.siteleaf.com/managing-content/metadata.html

It'd be nice to have more robust styles tho, maybe different icons or something. I like how [Jekyll does it](http://jekyllrb.com/docs/home/#helpful-hints) actually.

**Comment by sskylar** [comment]
star? lightbulb?

![](http://drp.mk/i/y3kcfpJKd1.png)
