### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by sskylar** [siteleaf/learn.siteleaf.com#22]
This site could use one, also might be good for our help docs.

e.g. https://gist.github.com/sskylar/a96d145d476589aeeaa0

**Comment by eturk** [comment]
Sitemaps (and RSS) are among those few Jekyll gems supported by GitHub Pages ([here](https://help.github.com/articles/atom-rss-feeds-for-github-pages/) and [here](https://help.github.com/articles/sitemaps-for-github-pages/)). We can probably point people using GitHub pages there and give the XML file templates to everyone else (which can be found [here](https://github.com/jekyll/jekyll-feed/blob/master/lib/feed.xml) and [here](https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml).

(Also applies to #23)
