### ISSUE TITLE
Pretty permalinks

### ISSUE THREAD

**Issue by sskylar** [siteleaf/learn.siteleaf.com#25]
Let's dump the `.html` in links (soon before we start linking to thinks and have broken links)

**Comment by larryfox** [comment]
@sawyerh Didn't like them for some reason. https://github.com/siteleaf/learn.siteleaf.com/commit/5c72c483db1ed619ddbe14bfe9bc1e974cbb0df7

**Comment by sskylar** [comment]
@sawyerh huh why? explain

**Comment by sawyerh** [comment]
Not true. For some reason I thought that was the default and you didn't need all of that in the config, my bad 🙈

**Comment by larryfox** [comment]
Fixed it earlier bb006eeb46d6
