### ISSUE TITLE
Add tips to optimizing Jekyll build time

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#40]
I don't have a comprehensive list of tips, but maybe we can start compiling one:

- Exclude `node_modules`, `bower_components`, etc: http://stackoverflow.com/questions/26855552/jekyll-compiling-seems-way-too-slow?answertab=votes#tab-top

**Comment by larryfox** [comment]
- Limit large `for` loops
- Limit nested `for` loops
