### ISSUE TITLE
Request: Better Examples of Why You'd Use Collections vs Posts

### ISSUE THREAD

**Issue by iChris** [siteleaf/learn.siteleaf.com#41]
(Not sure if you want this type of thing on here - feel free to move me elsewhere)

As a user first and coder second (or third or fourth), I'd appreciate a better explanation of when and why I might use collections instead of just throwing things into posts.

For a current project we're thinking of using Siteleaf for, I can't figure out which way to go and it feels like the wrong choice could mean a lot of work to fix. Or maybe I'm over-thinking it?

Selfish example: We're a podcast network and have Shows with episodes, hosts (who can be on multiple shows/episodes of shows), guests (who can be on multiple shows/episodes of shows), sponsors  (who can be on multiple shows/episodes of shows) and are struggling with how best to organize everything.

**Comment by eturk** [comment]
Thanks for the feedback! Our documentation is a work in progress, and we're currently working on a better collection page right now.

As for your problem, collections are definitely a great solution. You could make collections for `Hosts`, `Guests`, and `Sponsors`, and then a collection for each show. Pages will be generated for every document in these collections automatically as well.

To link them together, you can use a little trick with meta fields: if you name a field after a collection (e.g., `hosts`), the value for that field will autocomplete to the titles of the documents in that collection. This works for list meta fields as well, so you can reference multiple hosts or guests from a show.

For example, I made a collection called `People` and added two people (`Ethan Turkeltaub` and `Bill Nye`). I made another collection called `Teams`, and created a new team. When I create a new meta field called `people`, the value field turns into a dropdown with autocomplete.

<img width="616" alt="screen shot 2016-03-18 at 18 01 12" src="https://cloud.githubusercontent.com/assets/137037/13893322/b296cb06-ed33-11e5-8e44-e21d907acbee.png">

It's then possible for me to get the `People` documents and query by title using the `where` filter:

```liquid
site.people.docs | where "title":"Ethan Turkeltaub"
```

I hope this makes sense! If you need more help, just drop by [our Slack channel](http://chat.siteleaf.com/).
