### ISSUE TITLE
Settings info is incorrect

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#46]
We don't currently offer a `permalink` field by default

![image](https://cloud.githubusercontent.com/assets/371943/14111546/23629abe-f599-11e5-9d62-be7cec78e989.png)

Would it be more useful to change ["Settings"](http://learn.siteleaf.com/users-and-settings/settings/) to "Configuration" and explain how to configure your site using the `_config.yml` file instead? We could do a brief explaination then link to Jekyll for more info:

- https://jekyllrb.com/docs/configuration/
- https://jekyllrb.com/docs/permalinks/

We also probably want to show an example of how you access any site metadata you add through the settings page: `site.title`, `site.custom_metadata_key`, etc

**Comment by larryfox** [comment]
I would be in support of not even mentioning the site permalink setting. We could recommend defaults/collection permalinks instead, it can be more granular, and is a bit more obvious what's changing IMO.

The site permalink setting on it's own, not only changes the posts permalink, but also changes the suffix of pages and other documents. (`pretty` results in no `.html` extension, while the others do)
