### ISSUE TITLE
Move away from Swiftype

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#49]
Unless we want to pay Swiftype $299/mo (I don't think we do), we'll need to switch over to [Google CSE](https://cse.google.com/cse/) which has a [JSON API](https://developers.google.com/custom-search/json-api/v1/overview) we could use.

![image](https://cloud.githubusercontent.com/assets/371943/14955653/747af17e-1049-11e6-80bb-f8ffaa2dc925.png)

**Comment by eturk** [comment]
How long do we have before Swiftype stops working? Does it just work indefinitely, or do they cut off at 3 months or something?

**Comment by sawyerh** [comment]
They don't say

**Comment by eturk** [comment]
It looks like we'd need to pay for Google CSE as well. From the [JSON API](https://developers.google.com/custom-search/json-api/v1/overview#prerequisites) page:

> For CSE users, the API provides 100 search queries per day for free. If you need more, you may sign up for billing in the Developers Console. Additional requests cost $5 per 1000 queries, up to 10k queries per day.

I doubt we'd get to 10k queries per day, but we could rack up the charges pretty quickly.

**Comment by sawyerh** [comment]
Totally fine with that. Swiftype's cheapest options is $299/mo
