### ISSUE TITLE
Collection permalinks

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#51]
This is nitpicky, but now that we have a closer idea of the documentation structure, can we simplify some of the collection's permalinks:

- [x] `users-and-settings` -> `sites` (this is the one that bugs me the most)
- [x] `siteleaf-v2` -> `v2`
- [x] `managing-content` -> `content`
- [x] `theme-development` -> `themes`

You'll want to do a find-and-replace to make sure any inline links are also updated.

**Comment by eturk** [comment]
Reopening this. I don't think we can change `managing-content` to `content`: I think `content` maybe a reserved word in Jekyll.

**Comment by eturk** [comment]
Never mind, I'm an idiot — renamed the `_managing-content/` directory to `content/` instead of `_content/`.
