### ISSUE TITLE
Broken link from Manage > Settings page

### ISSUE THREAD

**Issue by caseyg** [siteleaf/learn.siteleaf.com#53]
`Manage > Settings` screen shows a link to:

![screen shot 2016-05-16 at 4 41 19 pm](https://cloud.githubusercontent.com/assets/462020/15303306/0f1bbb82-1b85-11e6-8537-adfe5e216f6e.png)

which directs to:

http://learn.siteleaf.com/managing-content/metadata/

but that page appears to have been moved here:

http://learn.siteleaf.com/content/metadata/

**Comment by eturk** [comment]
Thanks for letting us know! It should be fixed now.
