### ISSUE TITLE
Default fields

### ISSUE THREAD

**Issue by sskylar** [siteleaf/learn.siteleaf.com#58]
One of the top questions I get asked is how to add default fields so they show up for all posts. Specifically because they want these fields to show up in the admin by default.

I usually point them to this: https://gist.github.com/sskylar/4a782de7c8d080cf5db6

And mention its okay for default keys to have blank values, and also to take advantage of Smart Field names (which is already mentioned).

**Comment by sawyerh** [comment]
Currently there's a short blurb on this here: http://learn.siteleaf.com/content/metadata/#defining-default-fields

**Comment by sskylar** [comment]
Pretty buried though, shows up as the 6th entry if you search for "defaults". 

![](http://drp.mk/i/tvrw85n3C.png)

And people keep asking.
