### ISSUE TITLE
Show status?

### ISSUE THREAD

**Issue by larryfox** [siteleaf/learn.siteleaf.com#60]
I like how the github docs show the current status:

<img width="331" alt="screen shot 2016-05-25 at 3 59 02 pm" src="https://cloud.githubusercontent.com/assets/795026/15554397/fc407bec-2291-11e6-8f1a-8f18803968f1.png">

**Comment by sskylar** [comment]
Statuspage.io gives us a little widget:

https://6m245s2fvklg.statuspage.io/api/v2/status.json

(more options here: https://manage.statuspage.io/pages/6m245s2fvklg/status-widget)

via http://blog.statuspage.io/embed-system-status-within-your-webapp

![](https://statuspage-blog.s3.amazonaws.com/2014-08-01-status-embed/status-embed-tempo.png)

**Comment by larryfox** [comment]
Niiiice, how about something simple like this?

OK:
<img width="101" alt="screen shot 2016-05-25 at 4 42 31 pm" src="https://cloud.githubusercontent.com/assets/795026/15555698/e94cc242-2297-11e6-9960-fda3ee6283c2.png">

Minor:
<img width="108" alt="screen shot 2016-05-25 at 4 42 41 pm" src="https://cloud.githubusercontent.com/assets/795026/15555695/e946c162-2297-11e6-9e6c-584b6efea2ad.png">

Major:
<img width="96" alt="screen shot 2016-05-25 at 4 43 46 pm" src="https://cloud.githubusercontent.com/assets/795026/15555696/e94aa4ee-2297-11e6-9d37-86727fd768df.png">

Critical:
<img width="103" alt="screen shot 2016-05-25 at 4 42 51 pm" src="https://cloud.githubusercontent.com/assets/795026/15555697/e94c3ed0-2297-11e6-8e7c-89fe85115002.png">

**Comment by sawyerh** [comment]
merged

**Comment by sskylar** [comment]
Bring this back! If not in header, maybe in footer with text like this:

![](https://camo.githubusercontent.com/d034aa5cc41b02f5ab225f8fc05cc7928e1e0087/68747470733a2f2f737461747573706167652d626c6f672e73332e616d617a6f6e6177732e636f6d2f323031342d30382d30312d7374617475732d656d6265642f7374617475732d656d6265642d74656d706f2e706e67)
