### ISSUE TITLE
Update info on how to receive support

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/learn.siteleaf.com#66]
Can probably replace [this page](http://learn.siteleaf.com/v2/feedback/) with a "Getting Help" document under the "Getting Started" section, explaining how to get support if you're on a paid plan (click the chat button at the bottom of your site in Siteleaf) and provide info on how to join the Slack for community support (provided to all plans)

![image](https://cloud.githubusercontent.com/assets/371943/15780947/f2c781c8-2971-11e6-8db7-1a6cd24e9174.png)

**Comment by eturk** [comment]
> We should therefore remove the team@siteleaf.com email from v1 support and v2 support docs ([link](https://github.com/oakstudios/Siteleaf/commit/88b9260e72e8bd560c3fc154d5bc980442aa754b#commitcomment-17733398))
