### ISSUE TITLE
First line of some code blocks is slightly indented

### ISSUE THREAD

**Issue by justinjaywang** [siteleaf/learn.siteleaf.com#77]
![](http://cdn2.dropmark.com/40029/f05f3053a6c37140527b8b47d1e38e70f98ab6a9/Screenshot%202016-06-10%2017.45.38.png)

![](http://cdn2.dropmark.com/40029/a0a8a5ff700e201ca0f3274e51f8e2c87b90f4c0/Screenshot%202016-06-10%2017.54.48.png)

**Comment by sskylar** [comment]
I'm seeing this on siteleaf.com too:

![](http://drp.mk/i/xws47fQ0q.png)
