### ISSUE TITLE
How to use drag and drop sorting

### ISSUE THREAD

**Issue by sskylar** [siteleaf/learn.siteleaf.com#83]
You can sort in the interface: http://drp.mk/i/yBQX93m4Fw

But we don't tell you how to make this work in your theme:

```
​{% assign documents = site.collectionname | sort:'position' %}
​{% for document in documents %}
​...
​{% endfor %}
```

**Comment by sawyerh** [comment]
This was added https://learn.siteleaf.com/content/drag-and-drop-position/
