### ISSUE TITLE
Setting the default layout does not save

### ISSUE THREAD

**Issue by brettchalupa** [siteleaf/learn.siteleaf.com#86]
The quick version: When adding new posts, I want them to have the layout default to `post`, but the value does not get set upon post save unless the value is selected from the dropdown.

The details:

When [following the docs for setting default values](https://github.com/siteleaf/learn.siteleaf.com/blob/master/_content/defaults.markdown), the default value for the layout does not save to the frontmatter of the created markdown file. The layout only saves when selecting an item from the drop-down, even if the value appears to be prepropulated. Here is a gif showing the current way I get the layout to save:

![siteleaf-default-layout](https://cloud.githubusercontent.com/assets/928367/18356834/5281bb2e-75a3-11e6-8ca6-a8aabb0142d2.gif)

As seen in the gif, once a value is selected from the dropdown, the `x` appears. Before the selection, the value is pre-populated by does not save.

Here is the defaults in the site's `_config.yml`:

``` yml
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: 
```

Is there anything on my end that I need to change or more info I can provide? Is this the right place to open this issue? Thank you!

**Comment by sawyerh** [comment]
Moving to Slack discussion. Will re-open if the issue resides in the docs copy.
