### ISSUE TITLE
Don't see Collections in the cpanel

### ISSUE THREAD

**Issue by miguelpaz** [siteleaf/learn.siteleaf.com#89]
Should I assume a Page with subpages and and subposts is a Collection?

**Comment by sskylar** [comment]
Collections should show up in the left side bar. Here are some tutorials to get you up to speed: https://learn.siteleaf.com/getting-started/tutorials/

If that doesn't help, please contact support@siteleaf.com with a screenshot and description of what you see on your end.

**Comment by miguelpaz** [comment]
Just realized I was on v1, that's why. Sorry. Thanks for the reply.
